### ISSUE TITLE
请问怎么添加其他的模型

### ISSUE THREAD

**Issue by LPShigure** [xiaolaa2/stable-diffusion-webui-wd14-tagger#2]
除了这四种模型以外 可以自己添加其他模型吗

**Comment by LPShigure** [comment]
> 除了这四种模型以外 可以自己添加其他模型吗

**Comment by mingda27** [comment]
看我在这里的回复，我添加了别的模型
https://github.com/xiaolaa2/stable-diffusion-webui-wd14-tagger/issues/1#issuecomment-2277260696
